### ISSUE TITLE
QR-code scanner GUI

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwcx#3]
#### Objective:

Users should be able to quickly create a transaction by scanning QR-code with QWC address (and options).

#### Solution:

Develop _QR-code scanner_ page:
- user clicks on `Pay by QR-code` button;
- open _QR-code scanner_ page;
- user aligns the frame to scan QR-code;
- app validates QR-code;
- app redirects user to transfer page with predefined info from QR-code.

#### Value (for developers, product and/or users):

Users will be able to pay for something by simply scanning QR-code (this is a rather popular workflow).

#### DoD (Definition of Done):

Users are able to scan and pay using _QR-code scanner_ page.

**Comment by speqtr** [comment]
Preview:
<img width="432" alt="IMAGE001" src="https://user-images.githubusercontent.com/14371747/68088399-efd43e80-fe6f-11e9-82df-e506b92bfa1f.png">

**Comment by speqtr** [comment]
@exploshot, @nnian, @Xecute0101 and others are invited to comment and discuss current _QR-code scanner_ page GUI and propose improvements.

This page is really simple, but I thought it deserves a small part of attention before release too 🙂

**Comment by nnian** [comment]
I think there are no possible changes to a QR Code Scanner page. As long as the site can scan QR codes, everything is perfect.

**Comment by Xecute0101** [comment]
Fine by me.

**Comment by speqtr** [comment]
All feedback was taken into an account and updated GUI is already implemented. Further requests can be sent to #1 or by opening a separate issue on GitHub.
