### ISSUE TITLE
Transfer money GUI

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwcx#4]
#### Objective:

Users should be able to create a transaction by manually adding transaction data (recipient address, transfer amount, comment, etc).

#### Solution:

Develop _Transfer money_ page:

- open _Transfer money_ page;
- input recipient address, amount;
- (optional) input transaction ID;
- hit `Send` button;
- app validates transaction data and sends it to the QWC network.

#### Value (for developers, product and/or users):

Users will be able to transfer money by manually typing data.

#### DoD (Definition of Done):

Users are able to create transactions by manually typing data.

**Comment by speqtr** [comment]
Preview:
<img width="432" alt="IMAGE001" src="https://user-images.githubusercontent.com/14371747/68088612-eea41100-fe71-11e9-9612-47f71d15ae9b.png">
PS: I think it is really convenient to see total balance while creating a new transaction. It helps to be sure that there are enough funds before hitting `Send` button.

**Comment by speqtr** [comment]
ping @exploshot, @nnian, @Xecute0101 🙂

**Comment by exploshot** [comment]
Is there a recheck (do you wanna really send 200Bn QWC to QWCasd...as?) available like in the actual mobile wallet from me, or the GUI/Zero Wallet?

**Comment by speqtr** [comment]
> Is there a recheck (do you wanna really send 200Bn QWC to QWCasd...as?) available like in the actual mobile wallet from me, or the GUI/Zero Wallet?

Yes, sure. There is a warning at the bottom and a big popup dialog that asks for confirmation after pressing `Send` button.

And in one of the future versions there will be a small popup at the bottom of the screen with text like `Sending 0.01 QWC to QWCabc...z` and `Undo` button. So there will be extra 5 seconds for users if they want to cancel the transaction after confirming the `Send` action in dialog (like in GUI/Zero wallet).

**Comment by Xecute0101** [comment]
One of the issues that all current wallets have is that the total transaction amount is not correctly displayed like tx fees and developer donations into final balance. Like if I want to send 1,000,000 QWC, the total balance for this transaction will be 1,000,000 + all fees when confirming txs.

**Comment by Xecute0101** [comment]
Using a built-in finger print authorization or face id on iOS would be perfect. Undo Pop-up with delay will be great like when you exit any telegram accounts.

**Comment by speqtr** [comment]
> One of the issues that all current wallets have is that the total transaction amount is not correctly displayed like tx fees and developer donations into final balance. Like if I want to send 1,000,000 QWC, the total balance for this transaction will be 1,000,000 + all fees when confirming txs.

I agree. "Final amount" is something really important from user perspective. I will think on an interface adjustments for showing it on _Transfer money_ page.

**Comment by speqtr** [comment]
> Using a built-in finger print authorization or face id on iOS would be perfect.

I have it on my TODO list. I think we can add this feature as a "patch release" after `v1.0` is out.

**Comment by speqtr** [comment]
> Undo Pop-up with delay will be great like when you exit any telegram accounts.

True. It is really convenient 👍

**Comment by nnian** [comment]
Can I, as a user, only send QWC, for example 5Mio QWC to @speqtr , or can I also send $ 20 to @Xecute0101 and the amount will be converted into QWC?

**Comment by speqtr** [comment]
@nnian in the first version only QWC amount can be entered and approximate amount in USD (or other fiat currency) will be shown as a read-only information (under QWC amount).

After we properly test QWC<-->fiat rates in "read-only" format then (in one of the next versions) we will enable a new feature that will allow users to set transaction amount in almost any currency and automatically convert it to QWC.

**Comment by nnian** [comment]
> 
> 
> After we properly test QWC<-->fiat rates in "read-only" format [...] convert it to QWC.

Sounds great. I'm fine with that.

**Comment by speqtr** [comment]
All feedback was taken into an account and updated GUI is already implemented. Further requests can be sent to #1 or by opening a separate issue on GitHub.
