### ISSUE TITLE
Red envelopes

### ISSUE THREAD

**Issue by laotanAndzijun** [qwertycoin-org/qwcx#6]
Red envelopes are very attractive and can let a lot of people participate. Like wechat red envelopes, Chinese people like to rob red envelopes. I wonder if there will be in the future?

**Comment by Xecute0101** [comment]
Hongbao is more of a gift coupon in modern world.     It is like a paper walllet inside a red envelope if you were to give it in person.

**Comment by speqtr** [comment]
@Xecute0101, could you please add some more context to this issue? Or should I close it?

**Comment by Xecute0101** [comment]
We can close this issue.

**Comment by speqtr** [comment]
OK. Closing...

**Comment by speqtr** [comment]
OK. Closing...
